version: '3.8'
services:
  postgres_flask:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: flaskdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: userpassword
    ports: ["5432:5432"]
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d flaskdb"]
      interval: 5s
      timeout: 3s
      retries: 20

  backend:
    build: ./backend
    ports: 
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://user:userpassword@postgres_flask:5432/flaskdb
      FLASK_ENV: development
    depends_on:
      postgres_flask:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:5000/health || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30


  frontend:
    build:
      context: ./frontend
    container_name: bts_frontend
    environment:
      # exposée au frontend (Vite) si tu l'utilises dans ton code
      VITE_API_URL: http://backend:5000
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data:
