name: Security Scans

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare reports dir
        run: mkdir -p reports

      # ===== Build images =====
      - name: Build backend image
        run: docker build -t backend:local -f backend/Dockerfile backend

      - name: Build frontend image
        run: docker build -t frontend:local -f frontend/Dockerfile frontend

      # ===== Gitleaks (secrets dans le repo) =====
      - name: Run Gitleaks (JSON)
        run: |
          docker run --rm -v "${{ github.workspace }}:/path" zricethezav/gitleaks:latest \
            detect -s /path -f json -r /path/reports/gitleaks.json || true

      # ===== Trivy (images) =====
      - name: Trivy backend image → JSON
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: backend:local
          format: json
          output: reports/trivy-backend.json
          hide-progress: true

      - name: Trivy frontend image → JSON
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: frontend:local
          format: json
          output: reports/trivy-frontend.json
          hide-progress: true

      # ===== Snyk OSS (dépendances Python du backend) =====
      - name: Snyk Open Source (pip) → JSON
        if: ${{ env.SNYK_TOKEN != '' }}
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: >
            test --file=backend/requirements.txt
            --package-manager=pip
            --json-file-output=reports/snyk-oss-backend.json

      # ===== Snyk Container (images) =====
      - name: Snyk Container backend → JSON
        if: ${{ env.SNYK_TOKEN != '' }}
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: backend:local
          args: --file=backend/Dockerfile --json-file-output=reports/snyk-backend.json

      - name: Snyk Container frontend → JSON
        if: ${{ env.SNYK_TOKEN != '' }}
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: frontend:local
          args: --file=frontend/Dockerfile --json-file-output=reports/snyk-frontend.json

      # ===== (Optionnel) Convertir quelques JSON → HTML légers =====
      - name: Quick HTML for Gitleaks
        run: |
          python - << 'PY'
          import json,html,sys
          d=json.load(open('reports/gitleaks.json','r',encoding='utf-8'))
          body=f"<h1>Gitleaks</h1><pre>{html.escape(json.dumps(d,indent=2))}</pre>"
          open('reports/gitleaks.html','w',encoding='utf-8').write(f"<!doctype html><meta charset='utf-8'>{body}")
          PY

      # ===== Upload des artefacts =====
      - name: Upload all reports (JSON + HTML)
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: reports/*
